apiVersion: v1
kind: Service
metadata:
  name: search-service
spec:
  selector:
    app: search  # Match this with the label in the user-service pod
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003